name: google_maps_place_picker_nd
description: A customized fork of google_maps_place_picker_mb with additional features and maintenance. 
  A Flutter plugin which provides 'Picking Place' using Google Maps widget. (MB version)
version: 1.0.0
homepage: https://github.com/nitin-creative/google_maps_place_picker_nd

environment:
  sdk: ^3.0.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  google_api_headers: ^4.5.0
  google_maps_flutter: ^2.12.3
  flutter_google_maps_webservices: ^1.1.1
  http: ^1.1.0
  provider: ^6.1.5
  tuple: ^2.0.2
  uuid: ^4.5.1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

false_secrets:
  - /example/lib/keys.dart
  - /example/android/app/src/main/AndroidManifest.xml
  - /example/ios/Runner/AppDelegate.swift
